# -*- coding: utf-8 -*-
"""TS_govt_Ration_updated.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MPP3ukGeDSQh3O_YKTz5V4WmP98JYdHa

Telangana PDS Analytics: Multi-Dimensional Shop Performance Clustering and Anomaly Profiling
"""

!git clone https://github.com/sravanioffice1997-arch/Telangana_PDS_Analytics.git

import glob

transaction_files = glob.glob(
'/content/Telangana_PDS_Analytics/Transactions/*.csv'
)

card_files = glob.glob(
'/content/Telangana_PDS_Analytics/Card_Status/*.csv'
)

print(len(transaction_files))
print(len(card_files))

import pandas as pd
import glob

transaction_files = glob.glob(
'/content/Telangana_PDS_Analytics/Transactions/*.csv'
)

transactions_df = pd.concat(
    (pd.read_csv(f, low_memory=False)
     for f in transaction_files),
    ignore_index=True
)

transactions_df.shape

card_files = glob.glob(
'/content/Telangana_PDS_Analytics/Card_Status/*.csv'
)

Card_Status_df = pd.concat(
    (pd.read_csv(f, low_memory=False)
     for f in card_files),
    ignore_index=True
)

Card_Status_df.shape

fps_locations_df = pd.read_csv(
'/content/Telangana_PDS_Analytics/fps_locations.csv'
)

fps_locations_df.shape

print(transactions_df.shape)
print(Card_Status_df.shape)
print(fps_locations_df.shape)

transactions_unique = transactions_df.drop_duplicates(
    subset=['shopNo','distCode','month', 'year']
)

Card_Status_unique = Card_Status_df.drop_duplicates(
    subset=['shopNo','distCode','month', 'year']
)

fps_locations_unique = fps_locations_df.drop_duplicates(
    subset=['shopNo','distCode']
)

print(transactions_unique.shape)
print(Card_Status_unique.shape)
print(fps_locations_unique.shape)

master_df = transactions_unique.merge(
    Card_Status_unique,
    on=['shopNo','distCode','month', 'year'],
    how='left'
)

master_df = master_df.merge(
    fps_locations_unique,
    on=['shopNo','distCode'],
    how='left'
)

print(master_df.shape)

master_df.to_csv('master_df.csv', index=False)

master_df.info()

master_df.isnull().sum().sort_values(ascending=False)

# 1. Drop completely dead weight
master_df = master_df.drop(columns=['cardPoolType', 'mroAsoApprDate', 'cardTypeId'], errors='ignore')

# 2. fill missing categorical
metadata_cols = ['distName', 'officeName', 'address', 'fpsStatus', 'fpsType']
master_df[metadata_cols] = master_df[metadata_cols].fillna('Unknown')

# 3. Handle missing coordinates safely
master_df['longitude'] = master_df['longitude'].fillna(master_df['longitude'].median())
master_df['latitude'] = master_df['latitude'].fillna(master_df['latitude'].median())

"""# Exploratory Data Analysis

Trend Analysis: Plot the growth of "Other Shop Transactions" (portability) from 2023 to 2025.
"""

portability_trend = (
    master_df.groupby('year')['otherShopTransCnt']
    .sum()
    .reset_index()
)

print(portability_trend)

import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(8,5))

sns.lineplot(
    data=portability_trend,
    x='year',
    y='otherShopTransCnt',
    marker='o'
)

plt.xlabel('Year')
plt.ylabel('Other Shop Transactions')
plt.title('Growth of Portability Transactions (2023-2025)')

plt.show()

plt.figure(figsize=(8,5))

sns.barplot(
    data=portability_trend,
    x='year',
    y='otherShopTransCnt'
)

plt.xlabel('Year')
plt.ylabel('Other Shop Transactions')
plt.title('Growth of Portability Transactions (2023-2025)')

plt.show()

"""Correlation between Entitlement and Transactions"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8,6))

sns.scatterplot(
    data=master_df,
    x='totalRcs',
    y='noOfTrans'
)

plt.xlabel('Total Ration Cards (Entitlement)')
plt.ylabel('Number of Transactions (Actual Execution)')
plt.title('Relationship between Total Ration Cards and Transactions')

plt.show()

master_df[['totalRcs','noOfTrans']].corr()

"""A correlation score of 0.88 is mathematically considered a strong positive linear relationship. It tells you that a shop's operational workload isn't random—it is heavily and directly dictated by its allocation of cards. As the number of registered cardholders increases, the number of actual monthly distributions scales up almost perfectly alongside it.

Distribution Checks: Used histograms and boxplots to identify the distribution of commodities like Rice and Wheat across districts.
"""

master_df['totalRice'] = (
    master_df['riceAfsc']
    + master_df['riceFsc']
    + master_df['riceAap']
)

"""Histograms-Rice Distribution,Wheat Distribution"""

master_df['totalRice'] = (
    master_df['riceAfsc']
    + master_df['riceFsc']
    + master_df['riceAap']
)

plt.figure(figsize=(8,5))

sns.histplot(
    master_df['totalRice'],
    bins=50,
    kde=True
)

plt.title('Distribution of Rice')
plt.xlabel('Rice Quantity')
plt.show()

plt.figure(figsize=(8,5))

sns.histplot(
    master_df['wheat'],
    bins=50,
    kde=True
)

plt.title('Distribution of Wheat')
plt.xlabel('Wheat Quantity')
plt.show()

"""Boxplots, Rice and Wheat"""

plt.figure(figsize=(15,6))

sns.boxplot(
    data=master_df,
    x='distName',
    y='totalRice'
)

plt.xticks(rotation=90)
plt.title('Distribution of Rice Across Districts')
plt.xlabel('District')
plt.ylabel('Rice Quantity')

plt.show()

plt.figure(figsize=(15,6))

sns.boxplot(
    data=master_df,
    x='distName',
    y='wheat'
)

plt.xticks(rotation=90)
plt.title('Distribution of Wheat Across Districts')
plt.xlabel('District')
plt.ylabel('Wheat Quantity')

plt.show()

"""Seasonality: Check for spikes in transaction volume during specific months (festivals/harvest)."""

master_df['month'].unique()

monthly_trans = (
    master_df.groupby('month')['noOfTrans']
    .sum()
    .reset_index()
)

monthly_trans

plt.figure(figsize=(10,5))

sns.lineplot(
    data=monthly_trans,
    x='month',
    y='noOfTrans',
    marker='o'
)

plt.title('Monthly Transaction Volume')
plt.xlabel('Month')
plt.ylabel('Number of Transactions')

plt.show()

monthly_yearly = (
    master_df.groupby(['year','month'])['noOfTrans']
    .sum()
    .reset_index()
)

plt.figure(figsize=(12,6))

sns.lineplot(
    data=monthly_yearly,
    x='month',
    y='noOfTrans',
    hue='year',
    marker='o'
)

plt.title('Monthly Transaction Volume by Year')
plt.xlabel('Month')
plt.ylabel('Transactions')

plt.show()

pivot_table = monthly_yearly.pivot(
    index='year',
    columns='month',
    values='noOfTrans'
)

plt.figure(figsize=(12,4))

sns.heatmap(
    pivot_table,
    annot=True,
    fmt='.0f',
    cmap='YlGnBu'
)

plt.title('Seasonality of Transactions')
plt.show()

"""# Feature Engineering:

"""

import numpy as np
master_df['utilization_ratio'] = master_df['noOfTrans'] / master_df['totalRcs'].replace(0, np.nan)

master_df['rice_total'] = master_df['riceAfsc'] + master_df['riceFsc'] + master_df['riceAap']

master_df['rice_wheat_ratio'] = master_df['rice_total'] / master_df['wheat'].replace(0, np.nan)

volatility = master_df.groupby('shopNo')['noOfTrans'].std().reset_index()
volatility.rename(columns={'noOfTrans':'trans_volatility'}, inplace=True)
master_df = master_df.merge(volatility, on='shopNo', how='left')

master_df['trans_per_card'] = master_df['noOfTrans'] / master_df['totalRcs'].replace(0, np.nan)

master_df['total_commodity'] = (
    master_df['riceAfsc'] + master_df['riceFsc'] + master_df['riceAap'] +
    master_df['wheat'] + master_df['sugar'] + master_df['kerosene']
)

master_df['portability_ratio'] = (
    master_df['otherShopTransCnt'] /
    master_df['noOfTrans'].replace(0, np.nan)
)

shop_df = master_df.groupby('shopNo').agg({
   'noOfTrans':'mean',
    'totalRcs':'mean',
    'utilization_ratio':'mean',
    'portability_ratio':'mean',
    'totalRice':'mean',
    'total_commodity':'mean'
}).reset_index()

"""#Clustering & Analysis:

"""

#Step 3: Scale Features
from sklearn.preprocessing import StandardScaler

features = [
    'noOfTrans',

    'utilization_ratio',
    'portability_ratio',
    'totalRice',
    'total_commodity'
]

scaler = StandardScaler()

X_scaled = scaler.fit_transform(
    shop_df[features]
)

shop_df[features] = shop_df[features].fillna(0)

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

for k in range(2, 11):

    kmeans = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    labels = kmeans.fit_predict(X_scaled)

    score = silhouette_score(
        X_scaled,
        labels
    )

    print(f"K={k}, Silhouette Score={score:.4f}")

#Step 5: Build K-Means Model
kmeans = KMeans(
    n_clusters=2,
    random_state=42,
     n_init=10
)

shop_df['cluster'] = kmeans.fit_predict(X_scaled)

shop_df['cluster'].value_counts()

cluster_profile = shop_df.groupby('cluster')[features].mean()

cluster_profile

shop_cluster = shop_df[['shopNo', 'cluster']]

district_cluster = (
    master_df[['shopNo', 'distName_x']]
    .drop_duplicates()
    .merge(shop_cluster, on='shopNo')
)

pd.crosstab(
    district_cluster['distName_x'],
    district_cluster['cluster']
)

"""PCA"""

from sklearn.decomposition import PCA

pca = PCA(n_components=0.95)

X_pca = pca.fit_transform(X_scaled)

print(X_pca.shape)

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

kmeans = KMeans(
    n_clusters=2,
    random_state=42,
    n_init=10
)

labels = kmeans.fit_predict(X_pca)

score = silhouette_score(X_pca, labels)

print(score)

"""AgglomerativeClustering"""

from sklearn.cluster import AgglomerativeClustering
from sklearn.metrics import silhouette_score

agg = AgglomerativeClustering(n_clusters=2)

labels = agg.fit_predict(X_scaled)

score = silhouette_score(X_scaled, labels)

print(score)

import pandas as pd

# Assuming 'labels' contains the cluster assignments for each shop in shop_df (from X_scaled)
# First, add the new cluster labels to the shop_df DataFrame
shop_df['cluster'] = labels

# Now, create df_cluster by merging the original master_df with the shop_df containing the cluster information.
# This correctly aligns the cluster labels with the original DataFrame's rows based on 'shopNo'.
df_cluster = master_df.merge(shop_df[['shopNo', 'cluster']], on='shopNo', how='left')

features = [
    'noOfTrans',
    'utilization_ratio',
    'portability_ratio',
    'totalRice',
    'total_commodity'
]
cluster_profile = df_cluster.groupby('cluster')[features].mean()

print(cluster_profile)

cluster_size = df_cluster['cluster'].value_counts()

print(cluster_size)

cluster_summary = df_cluster.groupby('cluster')[features].agg([
    'mean',
    'median'
])

print(cluster_summary)

"""Cluster Profile Comparison"""

import matplotlib.pyplot as plt

cluster_profile.T.plot(
    kind='bar',
    figsize=(8,6)
)

plt.title('Cluster Profile Comparison')
plt.ylabel('Average Value')
plt.show()

print(cluster_profile)

df_cluster['cluster_name'] = df_cluster['cluster'].map({
    0: 'Standard Activity FPS Shops',
    1: 'High-Demand FPS Shops'
})

df_cluster.columns

print(df_cluster[['cluster', 'cluster_name']].head())

master_df

features = [
    'nooftrans',
    'utilization_ratio',
    'portability_ratio',
    'rice_total',
    'total_commodity'
]

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# Correcting the features list to match available columns in shop_df
features = [
    'noOfTrans',
    'utilization_ratio',
    'portability_ratio',
    'totalRice',
    'total_commodity'
]

# Fill any remaining NaNs in the selected features of shop_df with 0 before scaling.
# This ensures the input to KMeans is completely free of missing values.
X_scaled = scaler.fit_transform(shop_df[features].fillna(0))

from sklearn.ensemble import IsolationForest

iso = IsolationForest(
    contamination=0.02,
    random_state=42
)

shop_df['anomaly'] = iso.fit_predict(X_scaled)

shop_df['anomaly'].value_counts()

shop_df.groupby('anomaly')[features].mean().round(2)

shop_df['anomaly_score'] = iso.decision_function(X_scaled)

shop_df.sort_values('anomaly_score').head(20)

district_anomaly = (
    master_df[['shopNo','distName_x']]
    .drop_duplicates()
    .merge(
        shop_df[['shopNo','anomaly']],
        on='shopNo'
    )
)

district_anomaly[
    district_anomaly['anomaly'] == -1
]['distName_x'].value_counts()